spring:
  datasource:
    username: root
    password: tinh2003
    url: jdbc:mysql://localhost:3306/backendjava
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
project:
  poster: posters/
